# Generated by Django 4.1.5 on 2023-01-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='qayterdi',
            new_name='qaytardi',
        ),
    ]
