# Generated by Django 4.1.5 on 2023-01-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_rename_qayterdi_record_qaytardi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('narx', models.BigIntegerField()),
                ('kelgan_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nashriyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
            ],
        ),
        migrations.RenameField(
            model_name='record',
            old_name='telaba',
            new_name='talaba',
        ),
        migrations.AlterField(
            model_name='muallif',
            name='tirik',
            field=models.CharField(choices=[('ha', "yo'q"), ('ha', "yo'q")], max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='qaytardi',
            field=models.CharField(choices=[(True, False), (True, False)], max_length=50),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='bitiruvchi',
            field=models.CharField(choices=[(True, False), (True, False)], max_length=50),
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kitobs')),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.sotuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='kitobs',
            name='nashriyot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.nashriyot'),
        ),
    ]
