# Generated by Django 4.1.5 on 2023-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_kitobs_nashriyot_sotuvchi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='yosh',
            field=models.SmallIntegerField(default=56),
            preserve_default=False,
        ),
    ]
