# Generated by Django 4.1.5 on 2023-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_muallif_yosh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='tirik',
            field=models.CharField(choices=[('ha', 'ha'), ("yo'q", "yo'q")], max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='qaytardi',
            field=models.CharField(choices=[(True, True), (False, False)], max_length=50),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='bitiruvchi',
            field=models.CharField(choices=[(True, True), (False, False)], max_length=50),
        ),
    ]
