# Generated by Django 4.1.5 on 2023-01-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_alter_muallif_tirik_alter_record_qaytardi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='bitiruvchi',
            field=models.CharField(choices=[(True, True), (False, False)], default=False, max_length=50),
        ),
    ]
